import { CSSProperties } from 'react';

export const S: Record<string, CSSProperties> = {
  root: { minHeight: '100vh', background: '#f6f8fb', color: '#1e293b' },
  toast: { position: 'fixed', bottom: 32, left: '50%', transform: 'translateX(-50%)', background: '#1e293b', color: '#f1f5f9', padding: '12px 28px', borderRadius: 12, fontSize: 14, fontWeight: 500, zIndex: 999, boxShadow: '0 8px 32px rgba(0,0,0,.25)', animation: 'fadeUp .3s ease' },

  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 24px', background: 'linear-gradient(135deg, #0f2942 0%, #1e3a5f 50%, #2a4a72 100%)', color: '#fff', position: 'sticky', top: 0, zIndex: 50 },
  headerTitle: { fontSize: 18, fontWeight: 700, letterSpacing: '.02em' },
  headerSub: { fontSize: 12, opacity: 0.7, marginTop: 2 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 8 },
  backBtn: { background: 'rgba(255,255,255,.12)', border: 'none', color: '#fff', padding: '6px 14px', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontWeight: 500 },
  settingsBtn: { background: 'rgba(255,255,255,.15)', border: '1px solid rgba(255,255,255,.2)', color: '#fff', padding: '7px 16px', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontWeight: 500 },
  logoutBtn: { background: 'rgba(255,255,255,.08)', border: '1px solid rgba(255,255,255,.15)', color: 'rgba(255,255,255,.8)', padding: '6px 12px', borderRadius: 8, fontSize: 12, cursor: 'pointer', fontWeight: 400 },
  userBadge: { fontSize: 12, color: 'rgba(255,255,255,.7)' },

  stepper: { display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px 16px', background: '#fff', borderBottom: '1px solid #e8ecf1', overflowX: 'auto' },
  stepItem: { display: 'flex', alignItems: 'center', gap: 6 },
  stepCircle: { width: 28, height: 28, borderRadius: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700, flexShrink: 0, transition: 'all .2s' },
  stepLabel: { fontSize: 12, whiteSpace: 'nowrap' },
  stepLine: { width: 32, height: 2, borderRadius: 1, flexShrink: 0, margin: '0 4px' },

  homeMain: { maxWidth: 900, margin: '0 auto', padding: '24px 16px' },
  heroCard: { display: 'flex', alignItems: 'center', gap: 16, background: 'linear-gradient(135deg, #1e3a5f, #2a5a8f)', color: '#fff', borderRadius: 16, padding: '24px 28px', cursor: 'pointer', boxShadow: '0 4px 24px rgba(30,58,95,.2)' },
  heroIcon: { width: 52, height: 52, borderRadius: 14, background: 'rgba(255,255,255,.18)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26, fontWeight: 700, flexShrink: 0 },
  heroTitle: { fontSize: 17, fontWeight: 700 },
  heroDesc: { fontSize: 13, opacity: 0.8, marginTop: 4 },
  heroArrow: { fontSize: 22, opacity: 0.6, flexShrink: 0 },
  sectionTitle: { fontSize: 15, fontWeight: 700, margin: '28px 0 14px', color: '#334155' },
  recentGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 14 },
  recentCard: { background: '#fff', borderRadius: 14, padding: '18px 20px', border: '1px solid #e8ecf1' },
  recentCardHeader: { display: 'flex', alignItems: 'center', gap: 12 },
  avatar: { width: 40, height: 40, borderRadius: 12, background: 'linear-gradient(135deg, #1e3a5f, #3b6fa0)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, fontWeight: 700, flexShrink: 0 },
  avatar2: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 26, height: 26, borderRadius: 7, background: '#1e3a5f', color: '#fff', fontSize: 12, fontWeight: 700, marginRight: 8, verticalAlign: 'middle' },
  recentName: { fontSize: 15, fontWeight: 600 },
  recentMeta: { fontSize: 12, color: '#64748b' },
  recentDate: { fontSize: 12, color: '#94a3b8', marginTop: 10 },
  smallBtn: { padding: '6px 14px', borderRadius: 8, border: 'none', background: '#1e3a5f', color: '#fff', fontSize: 12, fontWeight: 600, cursor: 'pointer', marginTop: 10 },

  createMain: { maxWidth: 1280, margin: '0 auto', padding: '24px 16px 80px' },
  stepTitle: { fontSize: 18, fontWeight: 700, marginBottom: 8 },
  stepDesc: { fontSize: 14, color: '#64748b', marginBottom: 20, lineHeight: 1.6 },
  stepActions: { display: 'flex', gap: 12, justifyContent: 'flex-end', marginTop: 24, paddingTop: 16, borderTop: '1px solid #e8ecf1', flexWrap: 'wrap' as const },

  searchInput: { width: '100%', padding: '12px 16px', borderRadius: 10, border: '1px solid #d1d9e0', fontSize: 14, outline: 'none', background: '#fff', marginBottom: 16 },
  userList: { display: 'flex', flexDirection: 'column' as const, gap: 10 },
  userCard: { padding: '16px 20px', borderRadius: 14, border: '2px solid #e2e8f0', cursor: 'pointer', transition: 'all .15s' },
  userCardTop: { display: 'flex', alignItems: 'center', gap: 14 },
  userName: { fontSize: 16, fontWeight: 600 },
  userSub: { fontSize: 13, color: '#64748b' },
  checkMark: { width: 28, height: 28, borderRadius: 14, background: '#0f2942', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, fontWeight: 700 },
  userDetails: { marginTop: 10, paddingTop: 10, borderTop: '1px solid #f1f5f9', fontSize: 13, color: '#64748b', display: 'flex', flexDirection: 'column' as const, gap: 2 },

  modeSelector: { display: 'flex', gap: 12, marginBottom: 20, padding: '16px 20px', background: '#fff', borderRadius: 12, border: '1px solid #e8ecf1' },
  modeLabel: { fontSize: 13, fontWeight: 700, color: '#334155', marginBottom: 8 },
  modeRadio: { display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', padding: '10px 16px', borderRadius: 10, border: '2px solid #e2e8f0', fontSize: 13, fontWeight: 500 },
  modeRadioActive: { display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', padding: '10px 16px', borderRadius: 10, border: '2px solid #0f2942', background: '#f0f7ff', fontSize: 13, fontWeight: 700, color: '#0f2942' },

  sourceList: { display: 'flex', flexDirection: 'column' as const, gap: 8 },
  sourceCard: { display: 'flex', alignItems: 'center', gap: 14, padding: '14px 18px', borderRadius: 12, border: '2px solid #e2e8f0', cursor: 'pointer' },
  sourceIcon: { fontSize: 24, flexShrink: 0 },
  sourceName: { fontSize: 14, fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
  sourceMeta: { fontSize: 12, color: '#94a3b8' },
  checkbox: { width: 22, height: 22, borderRadius: 6, border: '2px solid #cbd5e1', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  existingNotice: { display: 'flex', alignItems: 'center', gap: 10, marginTop: 14, padding: '12px 16px', borderRadius: 10, background: '#faf5ff', border: '1px solid #e9d5ff', fontSize: 13, color: '#6b21a8' },

  analyzingOverlay: { position: 'fixed' as const, top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(15,41,66,.5)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 },
  analyzingCard: { background: '#fff', borderRadius: 20, padding: '40px 48px', textAlign: 'center' as const, boxShadow: '0 20px 60px rgba(0,0,0,.15)' },
  spinner: { width: 48, height: 48, border: '4px solid #e2e8f0', borderTopColor: '#1e3a5f', borderRadius: '50%', animation: 'spin .8s linear infinite', margin: '0 auto' },

  planSwitcher: { background: '#fff', borderRadius: 14, padding: '16px 20px', marginBottom: 16, border: '1px solid #e8ecf1' },
  planSwitcherLabel: { fontSize: 12, fontWeight: 700, color: '#64748b', marginBottom: 10 },
  planSwitcherButtons: { display: 'flex', gap: 8, flexWrap: 'wrap' as const },
  planSwitchBtn: { padding: '10px 18px', borderRadius: 10, border: '2px solid #d1d9e0', background: '#fff', fontSize: 13, fontWeight: 700, cursor: 'pointer', transition: 'all .15s' },
  planSummary: { marginTop: 12, padding: '10px 14px', background: '#f8fafc', borderLeft: '4px solid #2563eb', borderRadius: '0 8px 8px 0', fontSize: 13, color: '#475569', lineHeight: 1.6 },

  tableTabs: { display: 'flex', gap: 4, marginBottom: 0, borderBottom: '2px solid #0f2942' },
  tableTab: { padding: '10px 24px', borderRadius: '10px 10px 0 0', border: '1px solid #d1d9e0', borderBottom: 'none', background: '#f1f5f9', color: '#475569', fontSize: 14, fontWeight: 600, cursor: 'pointer' },
  tableTabActive: { padding: '10px 24px', borderRadius: '10px 10px 0 0', border: '2px solid #0f2942', borderBottom: '2px solid #fff', background: '#fff', color: '#0f2942', fontSize: 14, fontWeight: 700, cursor: 'pointer', marginBottom: -2, position: 'relative' as const, zIndex: 1 },

  formSheet: { background: '#fff', border: '1.5px solid #0f2942', borderTop: 'none', padding: '20px 24px', overflowX: 'auto' as const },
  sheetHeader: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12, paddingBottom: 8 },
  sheetTag: { display: 'inline-block', padding: '3px 12px', border: '1.5px solid #0f2942', background: '#fff', fontSize: 13, fontWeight: 700, color: '#0f2942' },
  sheetTitle: { flex: 1, textAlign: 'center' as const, fontSize: 17, fontWeight: 700, color: '#0f2942', textDecoration: 'underline' },
  sheetDate: { fontSize: 12, color: '#475569' },
  statusPill: { display: 'inline-block', padding: '3px 14px', border: '1px solid #475569', borderRadius: 0, fontSize: 12, color: '#1e293b' },

  formTable: { width: '100%', borderCollapse: 'collapse' as const, border: '1.5px solid #0f2942', fontSize: 13 },
  tdLabel: { border: '1px solid #475569', padding: '8px 10px', background: '#f1f5f9', fontWeight: 600, fontSize: 12, verticalAlign: 'middle', color: '#1e293b', whiteSpace: 'nowrap' as const },
  tdValue: { border: '1px solid #475569', padding: '8px 12px', verticalAlign: 'middle', color: '#1e293b', lineHeight: 1.6 },

  thMain: { border: '1px solid #475569', padding: '8px 6px', background: '#e2e8f0', fontWeight: 700, fontSize: 12, textAlign: 'center' as const, color: '#1e293b' },
  thSub: { border: '1px solid #475569', padding: '6px 4px', background: '#f1f5f9', fontWeight: 600, fontSize: 11, textAlign: 'center' as const, color: '#475569' },
  tdNeed: { border: '1px solid #475569', padding: '8px 10px', fontSize: 12, lineHeight: 1.6, background: '#fefce8' },
  tdGoal: { border: '1px solid #475569', padding: '6px 8px', fontSize: 12, lineHeight: 1.5 },
  tdService: { border: '1px solid #475569', padding: '6px 8px', fontSize: 12, lineHeight: 1.5 },

  periodCell: { border: '1px solid #475569', padding: '4px 2px', textAlign: 'center' as const, background: '#f1f5f9', fontWeight: 700, fontSize: 13, verticalAlign: 'middle' },
  timeCell: { border: '1px solid #475569', padding: '2px 6px', fontSize: 11, color: '#475569', verticalAlign: 'top', background: '#fafbfc' },
  scheduleCell: { border: '1px solid #94a3b8', padding: 2, height: 42, verticalAlign: 'top', position: 'relative' as const },
  serviceBlock: { display: 'block', padding: '3px 4px', borderRadius: 12, border: '1.5px solid', fontSize: 10, lineHeight: 1.3, textAlign: 'center' as const },
  dailyActCell: { border: '1px solid #475569', padding: '4px 10px', fontSize: 11, color: '#1e293b', verticalAlign: 'top', background: '#fafbfc' },

  exportGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, marginBottom: 24 },
  exportCard: { background: '#fff', borderRadius: 14, padding: '24px', border: '1px solid #e8ecf1', textAlign: 'center' as const },
  exportIcon: { fontSize: 40, marginBottom: 12 },
  exportTitle: { fontSize: 15, fontWeight: 700, marginBottom: 8 },
  exportDesc: { fontSize: 13, color: '#64748b', lineHeight: 1.6, marginBottom: 16 },

  primaryBtn: { padding: '12px 24px', borderRadius: 10, border: 'none', background: '#0f2942', color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  secondaryBtn: { padding: '12px 24px', borderRadius: 10, border: '1px solid #d1d9e0', background: '#fff', color: '#475569', fontSize: 14, fontWeight: 600, cursor: 'pointer' },
  disabledBtn: { padding: '12px 24px', borderRadius: 10, border: 'none', background: '#cbd5e1', color: '#94a3b8', fontSize: 14, fontWeight: 700, cursor: 'not-allowed' },
  saveBtn: { padding: '12px 28px', borderRadius: 10, border: 'none', background: '#0f2942', color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer', marginTop: 20 },

  settingsMain: { maxWidth: 800, margin: '0 auto', padding: '24px 16px' },
  settingsTabBar: { display: 'flex', gap: 4, marginBottom: 20, overflowX: 'auto' as const },
  settingsTab: { padding: '10px 18px', borderRadius: 10, border: '1px solid #d1d9e0', background: '#fff', color: '#475569', fontSize: 13, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap' as const },
  settingsTabActive: { padding: '10px 18px', borderRadius: 10, border: '2px solid #0f2942', background: '#f0f7ff', color: '#0f2942', fontSize: 13, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' as const },
  settingsPanel: { background: '#fff', borderRadius: 14, padding: '24px', border: '1px solid #e8ecf1' },
  fieldLabel: { display: 'block', fontSize: 13, fontWeight: 700, color: '#334155', margin: '16px 0 6px' },
  input: { width: '100%', padding: '10px 14px', borderRadius: 8, border: '1px solid #d1d9e0', fontSize: 14, outline: 'none' },
  textarea: { width: '100%', padding: '12px 14px', borderRadius: 8, border: '1px solid #d1d9e0', fontSize: 14, outline: 'none', resize: 'vertical' as const, lineHeight: 1.7 },
  promptHint: { marginTop: 12, padding: '12px 16px', borderRadius: 8, background: '#f8fafc', fontSize: 12, color: '#64748b', lineHeight: 1.7 },
};
